#spring:
#  datasource:
#    url: jdbc:mysql://office.nasbg.com:33062/java_bootcamp_3?createDatabaseIfNotExist=true
#    username: java_bootcamp_3
#    password: vSzUL2Na&q{g}zW
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#    show-sql: true


server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moonlight_hotel_db?createDatabaseIfNotExist=true
    username: root
    password: spring

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true